FROM openjdk:11-jre
COPY --from=backend_resolve-and-build:latest /dependencies/microservices/chat-service/target/chat-service-0.0.1-SNAPSHOT.jar .
COPY --from=backend_resolve-and-build:latest /env/backend-environment.yml /env/backend-environment.yml
ENTRYPOINT ["java", "-Dspring.config.import=file:/env/backend-environment.yml", "-jar", "chat-service-0.0.1-SNAPSHOT.jar"]


