FROM openjdk:11-jre
COPY --from=backend_resolve-and-build:latest /dependencies/microservices/chat-service/target/chat-service-0.0.1-SNAPSHOT.jar .
CMD ["java", "-jar", "chat-service-0.0.1-SNAPSHOT.jar"]


