server:
  port: ${media-microservice.port}
  error:
    include-message: always

spring:
  application:
    name: ${media-microservice.application-name}
  datasource: ${media-microservice.datasource}
  jpa: ${media-microservice.jpa}

eureka: ${service-registry-client}

