server:
  port: ${media-microservice.port}
  error:
    include-message: always

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: ${media-microservice.application-name}
  datasource: ${media-microservice.datasource}
  jpa: ${media-microservice.jpa}

eureka: ${service-registry-client}

