server:
  port: 9005

spring:
  application:
    name: MEDIA-SERVICE
  datasource:
    name:

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
