server:
  port: ${service-registry-server.port}

spring:
  application:
    name: SERVICE-REGISTRY

eureka:
  client:
    register-with-eureka: ${service-registry-server.eureka.client.register-with-eureka}
    fetch-registry: ${service-registry-server.eureka.client.fetch-registry}