FROM openjdk:11-jre
COPY --from=backend_resolve-and-build:latest /dependencies/microservices/notification-service/target/notification-service-0.0.1-SNAPSHOT.jar .
ENTRYPOINT ["java", "-jar", "./notification-service-0.0.1-SNAPSHOT.jar"]


