server:
  port: ${user-microservice.port}
  error:
    include-message: always

spring:
  application:
    name: ${user-microservice.application-name}
  datasource: ${user-microservice.datasource}
  jpa: ${user-microservice.jpa}

eureka: ${service-registry-client}

