server:
  port: ${main-controller.port}

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: ${main-controller.application-name}
  security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${keycloak.oauth2.resourceserver.jwt.issuer-uri}

eureka:
  client:
    register-with-eureka: ${service-registry-client.client.register-with-eureka}
    fetch-registry: ${service-registry-client.client.fetch-registry}
    service-url:
      defaultZone: ${service-registry-client.client.service-url.defaultZone}
