server:
  port: ${main-controller.port}

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: ${main-controller.application-name}
  security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${keycloak.oauth2.resourceserver.jwt.issuer-uri}

management:
  endpoints:
    web:
      exposure:
        include: ${management.endpoints.web.exposure.include}
