server:
  port: 9003
  error:
    include-message: always

spring:
  application:
    name: SHARING-SERVICE
  datasource:
    url: jdbc:postgresql://adventure-it-db.c9gozrkqo8dv.us-east-2.rds.amazonaws.com/adventureit?socketTimeout=5
    username: postgres
    password: 310PB!Gq%f&J
    hikari:
      maximum-pool-size: 2

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
