server:
  port: ${sharing-microservice.port}
  error:
    include-message: always

spring:
  application:
    name: ${sharing-microservice.application-name}
  datasource: ${sharing-microservice.datasource}
  jpa: ${sharing-microservice.jpa}

eureka: ${service-registry-client}

