FROM openjdk:11-jre
COPY --from=backend_resolve-and-build:latest /dependencies/microservices/recommendation-service/target/recommendation-service-0.0.1-SNAPSHOT.jar .
ENTRYPOINT ["java", "-jar", "./recommendation-service-0.0.1-SNAPSHOT.jar"]


