FROM openjdk:11-jre
COPY --from=backend_resolve-and-build:latest /dependencies/service-registry/target/service-registry-0.0.1-SNAPSHOT.jar .
ENTRYPOINT ["java", "-jar", "./service-registry-0.0.1-SNAPSHOT.jar"]