server:
  port: ${adventure-microservice.port}
  error:
    include-message: always

spring:
  application:
    name: ${adventure-microservice.application-name}
  datasource: ${adventure-microservice.datasource}
  jpa: ${adventure-microservice.jpa}

eureka: ${service-registry-client}

