server:
  port: 9001
  error:
    include-message: always

spring:
  application:
    name: ADVENTURE-SERVICE
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop

#  server.port = 9001
#  spring.application.name = adventure-microservice
#  spring.datasource.url=jdbc:postgresql://localhost:5000/postgres
#  spring.datasource.username=postgres
#  spring.datasource.password=password
#  spring.jpa.hibernate.ddl-auto=update
#  spring.jpa.show-sql=false
#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#  spring.jpa.properties.hibernate.format_sql=true

  datasource:
    url: jdbc:postgresql://adventure-it-db.c9gozrkqo8dv.us-east-2.rds.amazonaws.com/adventureit
    username: postgres
    password: 310PB!Gq%f&J
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

