server:
  port: 9001

spring:
  application:
    name: ADVENTURE-SERVICE
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop

#  server.port = 9001
#  spring.application.name = adventure-microservice
#  spring.datasource.url=jdbc:postgresql://localhost:5000/postgres
#  spring.datasource.username=postgres
#  spring.datasource.password=password
#  spring.jpa.hibernate.ddl-auto=update
#  spring.jpa.show-sql=false
#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#  spring.jpa.properties.hibernate.format_sql=true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

