FROM openjdk:11-jre
COPY --from=backend_resolve-and-build:latest /dependencies/microservices/user-service/target/user-service-0.0.1-SNAPSHOT.jar .
ENTRYPOINT ["java", "-jar", "./user-service-0.0.1-SNAPSHOT.jar"]


