server:
  port: ${notification-microservice.port}
  error:
    include-message: always

spring:
  application:
    name: ${notification-microservice.application-name}
  datasource: ${notification-microservice.datasource}
  jpa: ${notification-microservice.jpa}
  mail:
    host: ${notification-microservice.mail.host}
    port: ${notification-microservice.mail.port}
    user: ${notification-microservice.mail.user}
    password: ${notification-microservice.mail.password}
    smtp:
      auth: ${notification-microservice.mail.smtp.auth}
      connectionTimeout: ${notification-microservice.mail.smtp.connectionTimeout}
      timeout: ${notification-microservice.mail.smtp.timeout}
      writetimeout: ${notification-microservice.mail.smtp.writetimeout}
      startttls:
        enable: ${notification-microservice.mail.smtp.startttls.enable}

eureka: ${service-registry-client}

