server:
  port: ${notification-microservice.port}
  error:
    include-message: always

spring:
  application:
    name: NOTIFICATIOIN-MICROSERVICE
  datasource:
    url: ${notification-microservice.datasource.url}
    username: ${notification-microservice.datasource.username}
    password: ${notification-microservice.datasource.password}
    hikari:
      maximum-pool-size: ${notification-microservice.datasource.hikari.maximum-pool-size}
  jpa:
    hibernate:
      ddl-auto: ${notification-microservice.jpa.hibernate.ddl-auto}
    show-sql: ${notification-microservice.jpa.show-sql}
    properties:
      hibernate:
        dialect: ${notification-microservice.jpa.hibernate.properties.hibernate.dialect}
        format_sql: ${notification-microservice.jpa.hibernate.properties.hibernate.format_sql}
#  mail:
#    username: ${notification-microservice.mail.user}
#    host: ${notification-microservice.mail.host}
#    port: ${notification-microservice.mail.port}
#    password: ${notification-microservice.mail.password}
##    smtp:
##      auth: ${notification-microservice.mail.smtp.auth}
##      connectionTimeout: ${notification-microservice.mail.smtp.connectionTimeout}
##      timeout: ${notification-microservice.mail.smtp.timeout}
##      writetimeout: ${notification-microservice.mail.smtp.writetimeout}
##      startttls:
##        enable: ${notification-microservice.mail.smtp.startttls.enable}
##
#

eureka:
  client:
    register-with-eureka: ${service-registry-client.client.register-with-eureka}
    fetch-registry: ${service-registry-client.client.fetch-registry}
    service-url:
      defaultZone: ${service-registry-client.client.service-url.defaultZone}
