server:
  port: ${notification-microservice.port}
  error:
    include-message: always


spring:
  application:
    name: ${chat-microservice.application-name}
  datasource:
    url: ${chat-microservice.datasource.url}
    username: ${chat-microservice.datasource.username}
    password: ${chat-microservice.datasource.password}
    hikari:
      maximum-pool-size: ${chat-microservice.datasource.hikari.maximum-pool-size}
  jpa:
    hibernate:
      ddl-auto: ${chat-microservice.jpa.hibernate.ddl-auto}
    show-sql: ${chat-microservice.jpa.show-sql}
    properties:
      hibernate:
        dialect: ${chat-microservice.jpa.hibernate.properties.hibernate.dialect}
        format_sql: ${chat-microservice.jpa.hibernate.properties.hibernate.format_sql}
  mail:
    host: ${notification-microservice.mail.host}
    port: ${notification-microservice.mail.port}
    user: ${notification-microservice.mail.user}
    password: ${notification-microservice.mail.password}
    smtp:
      auth: ${notification-microservice.mail.smtp.auth}
      connectionTimeout: ${notification-microservice.mail.smtp.connectionTimeout}
      timeout: ${notification-microservice.mail.smtp.timeout}
      writetimeout: ${notification-microservice.mail.smtp.writetimeout}
      startttls:
        enable: ${notification-microservice.mail.smtp.startttls.enable}



eureka:
  client:
    register-with-eureka: ${service-registry-client.client.register-with-eureka}
    fetch-registry: ${service-registry-client.client.fetch-registry}
    service-url:
      defaultZone: ${service-registry-client.client.service-url.defaultZone}
  instance:
    hostname: ${service-registry-client.client.hostname}




