server:
  port: ${itinerary-microservice.port}
  error:
    include-message: always

spring:
  application:
    name: ${itinerary-microservice.application-name}
  datasource: ${itinerary-microservice.datasource}
  jpa: ${itinerary-microservice.jpa}

eureka: ${service-registry-client}

