server:
  port: 9010

spring:
  application:
    name: CHAT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Shivek01
    name: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost