server:
  port: ${chat-microservice.port}
  error:
    include-message: always

spring:
  application:
    name: ${chat-microservice.application-name}
  datasource: ${chat-microservice.datasource}
  jpa: ${chat-microservice.jpa}

eureka: ${service-registry.client}
