server:
  port: ${timeline-microservice.port}
  error:
    include-message: always

spring:
  application:
    name: ${timeline-microservice.application-name}
  datasource: ${timeline-microservice.datasource}
  jpa: ${timeline-microservice.jpa}

eureka: ${service-registry-client}

