FROM openjdk:11-jre
COPY --from=backend_resolve-and-build:latest /dependencies/microservices/media-service/target/media-service-0.0.1-SNAPSHOT.jar .
ENTRYPOINT ["java", "-jar", "./media-service-0.0.1-SNAPSHOT.jar"]


