server:
    port: ${budget-microservice.port}
    error:
        include-message: always

spring:
    application:
        name: ${budget-microservice.application-name}
    datasource:
        url: ${budget-microservice.datasource.url}
        username: ${budget-microservice.datasource.username}
        password: ${budget-microservice.datasource.password}
        hikari:
            maximum-pool-size: ${budget-microservice.datasource.hikari.maximum-pool-size}
    jpa:
        hibernate:
            ddl-auto: ${budget-microservice.jpa.hibernate.ddl-auto}
        show-sql: ${budget-microservice.jpa.show-sql}
        properties:
            hibernate:
                dialect: ${budget-microservice.jpa.hibernate.properties.hibernate.dialect}
                format_sql: ${budget-microservice.jpa.hibernate.properties.hibernate.format_sql}

eureka:
    client:
        register-with-eureka: ${service-registry-client.client.register-with-eureka}
        fetch-registry: ${service-registry-client.client.fetch-registry}
        service-url:
            defaultZone: ${service-registry-client.client.service-url.defaultZone}
