#    server.port = 9007
#        spring.application.name = budget-microservice
#
#        spring.jpa.hibernate.ddl-auto=update
#        spring.jpa.show-sql=false
#        spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#        spring.jpa.properties.hibernate.format_sql=true
#        spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#        spring.datasource.username=postgres
#        spring.datasource.password=Shivek01



server:
    port: 9007

spring:
    application:
        name: BUDGET-SERVICE

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
        instance:
            hostname: localhost
