server:
    port: ${budget-microservice.port}
    error:
        include-message: always

spring:
    application:
        name: ${budget-microservice.application-name}
    datasource: ${budget-microservice.datasource}
    jpa: ${budget-microservice.jpa}

eureka: ${service-registry.client}
