server:
  port: ${checklist-microservice.port}
  error:
    include-message: always

spring:
  application:
    name: ${checklist-microservice.application-name}
  datasource:
    url: ${checklist-microservice.datasource.url}
    username: ${checklist-microservice.datasource.username}
    password: ${checklist-microservice.datasource.password}
    hikari:
      maximum-pool-size: ${checklist-microservice.datasource.hikari.maximum-pool-size}
  jpa:
    hibernate:
      ddl-auto: ${checklist-microservice.jpa.hibernate.ddl-auto}
    show-sql: ${checklist-microservice.jpa.show-sql}
    properties:
      hibernate:
        dialect: ${checklist-microservice.jpa.hibernate.properties.hibernate.dialect}
        format_sql: ${checklist-microservice.jpa.hibernate.properties.hibernate.format_sql}

eureka:
  client:
    register-with-eureka: ${service-registry-client.client.register-with-eureka}
    fetch-registry: ${service-registry-client.client.fetch-registry}
    service-url:
      defaultZone: ${service-registry-client.client.service-url.defaultZone}
