server:
  port: ${checklist-microservice.port}
  error:
    include-message: always

spring:
  application:
    name: ${checklist-microservice.application-name}
  datasource: ${checklist-microservice.datasource}
  jpa: ${checklist-microservice.jpa}

eureka: ${service-registry-client}

