FROM openjdk:11-jre
COPY --from=backend_resolve-and-build:latest /dependencies/microservices/budget-service/target/budget-service-0.0.1-SNAPSHOT.jar .
COPY --from=backend_resolve-and-build:latest /env/backend-environment.yml /env/backend-environment.yml
ENTRYPOINT ["java", "-Dspring.config.import=file:/env/backend-environment.yml", "-jar", "budget-service-0.0.1-SNAPSHOT.jar"]


