FROM openjdk:11-jre
COPY --from=backend_resolve-and-build:latest /dependencies/microservices/budget-service/target/budget-service-0.0.1-SNAPSHOT.jar .
CMD ["java", "-jar", "budget-service-0.0.1-SNAPSHOT.jar"]


