FROM openjdk:11-jre
COPY --from=backend_resolve-and-build:latest /dependencies/microservices/location-service/target/location-service-0.0.1-SNAPSHOT.jar .
ENTRYPOINT ["java", "-jar", "./location-service-0.0.1-SNAPSHOT.jar"]


