FROM openjdk:11-jre
COPY --from=backend_resolve-and-build:latest /dependencies/main-controller/target/main-controller-0.0.1-SNAPSHOT.jar .
ENTRYPOINT ["java", "-jar", "./main-controller-0.0.1-SNAPSHOT.jar"]


