version: "3.3"

services:
  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: adventure-it-db.c9gozrkqo8dv.us-east-2.rds.amazonaws.com
      DB_DATABASE: adventureit
      DB_USER: postgres
      DB_SCHEMA: keycloak
      DB_PASSWORD: 310PB!Gq%f&J
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
