server:
  port: ${location-microservice.port}
  error:
    include-message: always

spring:
  application:
    name: ${location-microservice.application-name}
  datasource: ${location-microservice.datasource}
  jpa: ${location-microservice.jpa}

eureka: ${service-registry-client}

