name: Backend - Java CI with Maven (TESTING sprint_Three_MainController only)

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout sprint_Three_MicroController
        uses: action/checkout@v2
        with:
          repository: COS301-SE-2021/Adventure-IT
          ref: sprint_Three_MicroController
          token: ${{secrets.GitHub_PAT}}
      - name: Set Up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode test
        working-directory: backend
