name: Backend - Java CI with Maven

on:
  push:
    branches: 
    - master
    - development
    - sprint*
    - Sprint*
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get Repository
        uses: actions/checkout@v2
      - name: Set Up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        
        working-directory: backend/
        run: |
          chmod +x ./mvnw
          ./mvnw --batch-mode test
          
        
